### PR TITLE
(chore)dir_structure: directory structure for chaos observability

### PR DESCRIPTION
**Pull request by ksatchit**
- Propose initial directory structure for chaos-observability repo
- The observability folders (alerts, events, notifications, metrics, logs) are expected to contain user consumable artefacts & documentation around using them
- The utils folder is expected to contain any custom tooling, standard opensource components (deployment manifests of prometheus, event routers etc.,) etc., 

Signed-off-by: ksatchit <karthik.s@mayadata.io>

### CODE REVIEW

**Comment by chandankumar4** [comment]
Is this repo contain any code(Go) or just the different user configuration?

**Comment by rahulchheda** [comment]
According to my understanding, this repo will contain deployment YAML's for different components needed for Chaos Observability.
cc: @chandankumar4 @ksatchit

**Review by rahulchheda — APPROVED** [review]
Seems perfect for now.

**Review by imrajdas — APPROVED** [review]
lgtm

**Comment by ksatchit** [comment]
> Is this repo contain any code(Go) or just the different user configuration?

This is mostly user consumable artefacts @chandankumar4 . But there might be small tools placed here as well.

**Review by chandankumar4 — APPROVED** [review]

**Pull request merged**
